import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * ترتیب از پوشهٔ docs، عدد ابتدای نام پوشه، sidebar_position
 * و برچسب فارسی داخل _category_.json می‌آید.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
