name: Broken link
description: لینک داخلی یا خارجی یک صفحه کار نمی‌کند.
title: "fix: broken link"
labels:
  - documentation
body:
  - type: input
    id: source
    attributes:
      label: صفحهٔ مبدأ
    validations:
      required: true
  - type: input
    id: target
    attributes:
      label: لینک خراب
    validations:
      required: true
